# Generated by Django 5.2.10 on 2026-01-14 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_lb', models.IntegerField(default=0, help_text='Peso total del cilindro lleno')),
                ('tara_lb', models.IntegerField(default=0, help_text='Peso del cilindro vacío')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre pendiente', max_length=100)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre pendiente', max_length=100)),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Tipo pendiente', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cilindro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='Codigo pendiente', max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Disponible', max_length=50)),
                ('capacidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trazabilidad.capacidad')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trazabilidad.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre pendiente', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad.tipoactividad')),
            ],
        ),
    ]
