# Generated by Django 5.2.10 on 2026-01-19 00:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacidad',
            name='peso_lb',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Peso total del cilindro lleno', max_digits=6),
        ),
        migrations.AlterField(
            model_name='capacidad',
            name='tara_lb',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Peso del cilindro vacío', max_digits=6),
        ),
    ]
