# Generated by Django 5.2.10 on 2026-01-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0002_alter_capacidad_peso_lb_alter_capacidad_tara_lb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capacidad',
            old_name='peso_lb',
            new_name='peso_total_kg',
        ),
        migrations.RenameField(
            model_name='capacidad',
            old_name='tara_lb',
            new_name='tara_kg',
        ),
        migrations.AddField(
            model_name='capacidad',
            name='referencia',
            field=models.CharField(blank=True, help_text='Ej: Cilindro 20 lb', max_length=100, null=True),
        ),
    ]
