# Generated by Django 5.2.14 on 2026-05-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('codigo_hex', models.CharField(blank=True, max_length=7, verbose_name='Código Hex')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('meta', models.PositiveIntegerField(verbose_name='Meta de cilindros')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meta Diaria',
                'verbose_name_plural': 'Metas Diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SalidaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad de cilindros')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salida Diaria',
                'verbose_name_plural': 'Salidas Diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCilindro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Capacidad (kg)')),
                ('referencia', models.CharField(blank=True, max_length=50, verbose_name='Referencia')),
            ],
            options={
                'verbose_name': 'Tipo de Cilindro',
                'verbose_name_plural': 'Tipos de Cilindro',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cilindro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_niif', models.CharField(max_length=50, unique=True, verbose_name='Código NIIF')),
                ('tara', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tara (kg)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trazapp.color', verbose_name='Color')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trazapp.tipocilindro', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Cilindro',
                'verbose_name_plural': 'Cilindros',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('cilindro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='trazapp.cilindro', verbose_name='Cilindro')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
