# Generated by Django 5.2.14 on 2026-07-17 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('cilindro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='trazapp.cilindro', verbose_name='Cilindro')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
