# Generated by Django 5.2.14 on 2026-07-25 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazapp', '0002_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cilindro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='trazapp.cilindro', verbose_name='Cilindro')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='trazapp.tipoactividad', verbose_name='Tipo de actividad')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
