# Generated by Django 5.2.10 on 2026-01-21 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCilindro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado del cilindro',
                'verbose_name_plural': 'Estados del cilindro',
            },
        ),
        migrations.CreateModel(
            name='Cilindro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cilindros', to='cilindros.estadocilindro')),
            ],
            options={
                'verbose_name': 'Cilindro',
                'verbose_name_plural': 'Cilindros',
            },
        ),
    ]
